version: '4.0'

actions:
#########################
#  Flu vax data quality #
#########################

  extract_flu:
    run: ehrql:v1 generate-dataset analysis/flu/1_flu_dataset_definition.py
      --output output/outputs_flu/extract_flu:arrow
      #--dummy-data-file analysis/1-extract/dummy-data/dummy_varying.arrow
    outputs:
      highly_sensitive:
        cohort: output/outputs_flu/extract_flu/*.arrow

  report_data_quality_flu:
    run: r:v2 analysis/flu/2_flu_data_quality.R
    needs: [extract_flu]
    outputs:
      moderately_sensitive:
        csv: output/outputs_flu/flu_data_quality/*.csv
